# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kindling < Formula
  desc "Local Kubernetes dev environments powered by Kind"
  homepage "https://github.com/kindling-sh/kindling"
  version "0.4.1"
  license "Apache-2.0"

  depends_on "kind"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.1/kindling_0.4.1_darwin_amd64.tar.gz"
      sha256 "6e71d7ea7d06469f73f5f381b9f2b7b373b70694b44b3086ec4208e5c9c9f960"

      def install
        bin.install "kindling"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.1/kindling_0.4.1_darwin_arm64.tar.gz"
      sha256 "ab3e1ace708925d9d537c9fa8a60bd393fc52adf07db7eb66604a138203c5d4b"

      def install
        bin.install "kindling"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.1/kindling_0.4.1_linux_amd64.tar.gz"
      sha256 "9eea665ea4814d9cf9ecd6732c77898797513bff931c07cda6fc0346bce6ff5c"
      def install
        bin.install "kindling"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.1/kindling_0.4.1_linux_arm64.tar.gz"
      sha256 "5da672810021ced5257cc2dade15b845b5e4d1a2e98b272abaa1a00559e5303d"
      def install
        bin.install "kindling"
      end
    end
  end

  test do
    system "#{bin}/kindling", "version"
  end
end
