# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kindling < Formula
  desc "Local Kubernetes dev environments powered by Kind"
  homepage "https://github.com/kindling-sh/kindling"
  version "0.4.2"
  license "Apache-2.0"

  depends_on "kind"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.2/kindling_0.4.2_darwin_amd64.tar.gz"
      sha256 "7c9f67153b79a0bc08c9cd89880b2ad88932da792b0a2b83dd1dc1341062107f"

      def install
        bin.install "kindling"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.2/kindling_0.4.2_darwin_arm64.tar.gz"
      sha256 "b6260ee78caf86d0785179102b2dc1a01dc99de0d4f97dd65b29339e05b932bd"

      def install
        bin.install "kindling"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.2/kindling_0.4.2_linux_amd64.tar.gz"
      sha256 "198f5aaf73427a0e3c5bc0fc42411a33edef87176c1b9fcf2634d7985f155a77"
      def install
        bin.install "kindling"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.4.2/kindling_0.4.2_linux_arm64.tar.gz"
      sha256 "8dd5c5bc02da4eb7c11d6dc562977d129f8091c2374e70b0b582cfa1013baf5a"
      def install
        bin.install "kindling"
      end
    end
  end

  test do
    system "#{bin}/kindling", "version"
  end
end
