# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kindling < Formula
  desc "Local Kubernetes dev environments powered by Kind"
  homepage "https://github.com/kindling-sh/kindling"
  version "0.11.2"
  license "Apache-2.0"

  depends_on "kind"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.11.2/kindling_0.11.2_darwin_amd64.tar.gz"
      sha256 "b94c5f9f22166d406a3842b4d349c972bc68e101646f0904c8bc44830d2b5e93"

      define_method(:install) do
        bin.install "kindling"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.11.2/kindling_0.11.2_darwin_arm64.tar.gz"
      sha256 "06be92a9d9f1c871a8051f4dc54cc8913775a2e9ab08495f55e1e589ae024e50"

      define_method(:install) do
        bin.install "kindling"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.11.2/kindling_0.11.2_linux_amd64.tar.gz"
      sha256 "fbf6e591a9b67ba9e000597c25af50572540d6ff889ee4a99a7024cd01485999"
      define_method(:install) do
        bin.install "kindling"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kindling-sh/kindling/releases/download/v0.11.2/kindling_0.11.2_linux_arm64.tar.gz"
      sha256 "332b551eb11ee9b0eb1422ef9d7dc4d03be901e81785c7dfe50435c2630a2aa1"
      define_method(:install) do
        bin.install "kindling"
      end
    end
  end

  test do
    system "#{bin}/kindling", "version"
  end
end
